#+TITLE: Application for Savannah

# Copyright (C) 2020 Corwin Brust, Erik C. Elmshauser, Jon Lincicum, Hope Christiansen

Savannah is the project hosting solution provided by the Free Software foundation.

This document represents our (dungeon-mode, the project and product
team) application to host with and authoritatively publish via
Savannah.

This file is a part of dungeon-mode.  It is not a part of GNU Emacs.
This softare is released under the GNU Public Licence version three
or, at your disgression, any newer version of the GNU Public
License.  For specific terms please see [[LICENSE]] at end-of-file.

The initial application web-form is on gnu's web-site:

  https://savannah.gnu.org/register/

Which provides some additional advice:

  http://savannah.gnu.org/maintenance/HowToGetYourProjectApprovedQuickly/

You must have an account to register a project.  Accounts expire
quickly (within days) if not used for example to report a bug or
create a project.

* Document Scope

The above links as well as the body of this document relate to hosting
'dungeon-mode' on GNU Savannah.

This refers to providing a repository for the source code and
deployable artifacts of dungeon-mode "core". Generally this is meant
to include all of the source material for the default game, the elisp
or C sources for the game, and any other sources and configuration
needed for SDLC as well as the source materials for authoritative
documentation of each of these.  In this context "game" and "core"
both mean all of the features provided by dungeon-mode, for example
those for content authoring and print publication.

This is a separate process from (and one not implicitly linked to)
offering our project sources (e.g. transfer of the copyright for the
above same work) to GNU.  Source donation has a [[https://www.gnu.org/help/evaluation.html][separate application]].

* ~20-lines technical description
** Detail and Clarification
 * What is your project?
(purpose, topic, programming language...)
 * What is special about it?
** Notes
** Response

Create free (as in freedom) RPGs with GNU Emacs.  And then play them.

We want to:
  1. Create, publish and play RPGs without any costs now or ever.
  2. Own all our data and understand our rights when we use other
     people's content and when we share content, especially online.
  3. Learn from self-documenting software and heuristic features that
     maximize universal design opportunities improve RPG accessibility.
  4. Evangelize Free Software and GNU and drive adaptation by gamers
     by providing a single free platform e.g., whether for
     interactively joining a shared world across a network connection
     or at a table or while preparing a commercial work for binding.
  5. Play and create with the fewest possible assumptions, for example
     the presence of a window manager, access to a network, or use of
     a restricted or proprietary operating system or application.
  6. Maintain and distribute a "core" (meaning minimum original) set
     of technical components to support interactive play and authoring
     and provide a basis for creating original game experiences.
  7. Enable and support peer-to-peer and distributed content sharing
     free from any implicit oversight.  If approved, the dungeon-mode
     repository will include neither user supplied content nor game
     sources except for the "Default Dungeon" which source materials
     share the copyright and licensing terms of the of the project.
  8. If otherwise successful, enhance the GNU tool-chain of Free Software
     with additional audio and video conferencing capabilities
     especially for gaming and empower users to manage such streams
     from GNU Emacs and, e.g. while playing.  While these would likely
     culminate in new projects initial research may occur at this one.
  9. If otherwise successful, fork GNU Emacs and other GNU projects to
     create a mobile first information centric heuristic operating
     system focused on user freedom and privacy, e.g. to dungeon with.

* Other license, details
** Detail and Clarification
** Notes
** Response

In discussion and with support from FSF directory community/proponents
we have recently updated from GLPv3 to GPLv3+ in order to provide
users and others the ability, at their option, to select newer terms
which may address circumstance not anticipated by GLPv3.

* Checkboxes
 Checklist - see [[http://savannah.gnu.org/maintenance/HowToGetYourProjectApprovedQuickly/][How To Get Your Project Approved Quickly]]

 * [X] My project runs primarily on a completely free OS
 * [X] My license is compatible with the GNU GPL or GFDL
 * [X] My dependencies are compatible with my project license
 * [X] All my files include valid copyright notices
 * [X] All my files include a license header [1] [2]
 * [ ] Origin and license of media files is specified
 * [ ] My tarball includes a copy of the license
 * [ ] I read carefully and don't check this one
 * [ ] I agree with the hosting requirements

** Detail and Clarification
** Notes
** Response

* Dependencies
** Detail and Clarification

name + license + website for each dependency

** Notes
** Response

* Other Comments
** Detail and Clarification
** Notes
** Response

* LICENSE

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
