#+TITLE: Map Styles
#+PROPERTIES:
 :Version: 0.01
 :Author: Erik Elmshauser
 :Created: 2020/04/16
 :END:

This file is a part of dungeon-mode.  It is not a part of GNU Emacs.
This softare is released under the GNU Public Licence version three
or, at your disgression, any newer version of the GNU Public
License.  For specific terms please see [[LICENSE]] at end-of-file.

* Overview

This file is designed to define the appearance of the various SVG paths used to render the map.

* Map Path Styles
 :PROPERTIES:
   :name: map-styles
   :MAP-FEATURES: t
   :ETL: style
 :END:

# #+NAME: Map-Styles
| Style       | Key          | Value    |
|-------------+--------------+----------|
| path        | fill         | "none"   |
|             | stroke       | "black"  |
|             | stroke-width | 1        |
|             |              |          |
| water       | fill         | "blue"   |
|             | stroke       | "none"   |
|             |              |          |
| beach       | fill         | "Yellow" |
|             | stroke       | "none"   |
|             |              |          |
| Decorations | fill         | "cyan"   |
|             | stroke       | "none"   |
|             |              |          |
| stairs      | fill         | "Pink"   |
|             | stroke       | "none"   |
|             |              |          |

* LICENSE

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
